Repository ocp-power-automation/ocp4-playbooks, pull requests merged in 2020-09, with the labels that each got.

#52 Add contribution guide
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DCO1.1.txt
Labels: documentation

#65 Install gcc package
  playbooks/roles/ocp-customization/tasks/main.yaml
Labels: backport

#64 Install gcc package
  playbooks/roles/ocp-customization/tasks/main.yaml
Labels: bug
