Repository ocp-power-automation/ocp4-playbooks, pull requests merged in 2022-04, with the labels that each got.

#157 Notice for EOL (Full Support)
  README.md
Labels: size/XS, lgtm

#158 Notice for EOL (Full Support)
  README.md
Labels: size/XS, lgtm

#159 Notice for EOL (Full Support)
  README.md
Labels: size/XS, approved, lgtm

#160 csi driver installation
  examples/csi_driver_install_vars.yaml
  playbooks/csi_driver_config.yaml
  playbooks/csi_driver_install.yaml
  playbooks/roles/csi-driver-config/README.md
  playbooks/roles/csi-driver-install/README.md
  playbooks/roles/csi-driver-install/defaults/main.yaml
  playbooks/roles/csi-driver-install/tasks/config.yaml
  playbooks/roles/csi-driver-install/tasks/install.yaml
  playbooks/roles/csi-driver-install/tasks/main.yaml
Labels: kind/feature, approved, lgtm, size/L
